### ISSUE TITLE
NO_ACTIVE_DEVICE Error

### ISSUE THREAD

**Issue by plovlover** [mmattDonk/TwitchTunes#73]
I basically don't know what makes this error happen...

`23:21:43 ERROR    spotipy.client - HTTP Error for POST to                                                  client.py:262
                  https://api.spotify.com/v1/me/player/queue?uri=spotify:track:0yB4jrSwN0bFtFRDR5vyMj with
                  Params: {} returned 404 due to Player command failed: No active device found
Ignoring exception in command: http status: 404, code:-1 - https://api.spotify.com/v1/me/player/queue?uri=spotify:track:0yB4jrSwN0bFtFRDR5vyMj:
 Player command failed: No active device found, reason: NO_ACTIVE_DEVICE:
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\spotipy\client.py", line 245, in _internal_call
    response.raise_for_status()
  File "C:\Python310\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.spotify.com/v1/me/player/queue?uri=spotify:track:0yB4jrSwN0bFtFRDR5vyMj`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\twitchio\ext\commands\core.py", line 217, in invoke
    await self._callback(*args, *context.args, **context.kwargs)
  File "C:\plovlover-assets\TwitchTunes-1.4.0\bot.py", line 340, in songrequest_command
    await self.chat_song_request(ctx, song, song_uri, album=False)
  File "C:\plovlover-assets\TwitchTunes-1.4.0\bot.py", line 414, in chat_song_request
    sp.add_to_queue(song_uri)
  File "C:\Python310\lib\site-packages\spotipy\client.py", line 1888, in add_to_queue
    return self._post(endpoint)
  File "C:\Python310\lib\site-packages\spotipy\client.py", line 302, in _post
    return self._internal_call("POST", url, payload, kwargs)
  File "C:\Python310\lib\site-packages\spotipy\client.py", line 267, in _internal_call
    raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 404, code:-1 - https://api.spotify.com/v1/me/player/queue?uri=spotify:track:0yB4jrSwN0bFtFRDR5vyMj:
 Player command failed: No active device found, reason: NO_ACTIVE_DEVICE`

**Comment by mmattbtw** [comment]
you need to be actively playing something on spotify before a user uses a command
