### ISSUE TITLE
Twitch Channel points error

### ISSUE THREAD

**Issue by spofoh** [mmattDonk/TwitchTunes#81]
I put the reward name in the .env and then i want to start the bot and this error came

Traceback (most recent call last):
  File "C:\Users\llm\Desktop\TwitchSongBot\bot.py", line 499, in <module>
    twitch = Twitch(os.environ.get("client_id"), os.environ.get("client_secret"))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\llm\AppData\Local\Programs\Python\Python311\Lib\site-packages\twitchAPI\twitch.py", line 168, in __init__
    self.authenticate_app(target_app_auth_scope if target_app_auth_scope is not None else [])
  File "C:\Users\llm\AppData\Local\Programs\Python\Python311\Lib\site-packages\twitchAPI\twitch.py", line 436, in authenticate_app
    self.__generate_app_token()
  File "C:\Users\llm\AppData\Local\Programs\Python\Python311\Lib\site-packages\twitchAPI\twitch.py", line 408, in __generate_app_token
    raise MissingAppSecretException()
twitchAPI.types.MissingAppSecretException

**Comment by spofoh** [comment]
nvm got it fixed
